Spike upload scripts

diff --git a/s3d b/s3d
--- a/s3d
+++ b/s3d
@@ -1,14 +1,53 @@
 #!/usr/bin/env bash
 
+DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+
+# Colors
+GREEN="\033[0;32m"
+BLUE="\033[0;34m"
+GREY="\033[1;30m"
+CYAN="\033[0;36m"
+RED="\033[0;31m"
+YELLOW="\033[0;33m"
+NO_COLOR="\033[0m"
+BOLD="\033[1m"
+
+function displayHelpText {
+  text=$(cat <<-EOF
+
+  Usage:
+
+    s3d <config-file>
+\n
+EOF
+)
+  echo -e "$text"
+}
+
+function confirm {
+  read -p "Are you sure? " -n 1 -r USER_REPLY
+  if [[ $USER_REPLY =~ ^[Yy]$ ]]
+  then
+    echo ""
+  else
+    echo -e "$RED\n\nDeploy aborted\n$NO_COLOR"
+    exit 1
+  fi
+}
+
+path="$(readlink $DIR/s3d | xargs dirname )"
+
 command="$1"
 case "$command" in
 "" )
-  echo -e "\nUsage:  \n\n"
+  displayHelpText
   ;;
 "-h" | "--help" )
-  echo -e "\nUsage help:  \n\n"
+  displayHelpText
   ;;
 * )
-  echo -e "Executing $command"
+  $path/scripts/plan.rb $2
+  confirm
+  $path/scripts/execute.rb $2
   ;;
 esac
